name: obfuscateflutter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  intl: ^0.19.0
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
